# Generated by Django 5.2.3 on 2025-06-28 11:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('type', models.CharField(choices=[('КНИГА', 'Книга'), ('МУЗЫКА', 'Музыка'), ('ФИЛЬМ', 'Фильм'), ('СЕРИАЛ', 'Сериал'), ('МУЛЬТФИЛЬМ', 'Мультфильм'), ('ДРУГОЕ', 'Другое')], default='OTHER', max_length=20)),
            ],
            options={
                'unique_together': {('name', 'type')},
            },
        ),
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quote', models.TextField()),
                ('likes', models.PositiveIntegerField(default=0)),
                ('dislikes', models.PositiveIntegerField(default=0)),
                ('views', models.PositiveIntegerField(default=0)),
                ('prob_rate', models.PositiveIntegerField(default=2)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.source')),
            ],
        ),
        migrations.CreateModel(
            name='ViewCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session', models.CharField(db_index=True, default='0', max_length=150, verbose_name='Session')),
                ('quote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.quote')),
            ],
            options={
                'unique_together': {('quote', 'session')},
            },
        ),
    ]
