# Generated by Django 5.2.3 on 2025-06-27 13:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.TextField(max_length=200)),
                ('type', models.CharField(choices=[('BOOK', 'Book'), ('MUSIC', 'Music'), ('MOVIE', 'Movie'), ('SERIES', 'Series'), ('CARTOON', 'Cartoon'), ('OTHER', 'Other')], default='OTHER', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quote', models.TextField()),
                ('likes', models.PositiveIntegerField(default=0)),
                ('dislikes', models.PositiveIntegerField(default=0)),
                ('views', models.PositiveIntegerField(default=0)),
                ('prob_rate', models.FloatField(default=0.01)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.source')),
            ],
        ),
        migrations.CreateModel(
            name='ViewCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(verbose_name='IP Address')),
                ('quote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.quote')),
            ],
            options={
                'unique_together': {('quote', 'ip_address')},
            },
        ),
    ]
