# Generated by Django 5.2.3 on 2025-06-27 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='source',
            field=models.CharField(max_length=200),
        ),
        migrations.AddField(
            model_name='quote',
            name='source_type',
            field=models.CharField(choices=[('BOOK', 'Book'), ('MUSIC', 'Music'), ('MOVIE', 'Movie'), ('SERIES', 'Series'), ('CARTOON', 'Cartoon'), ('OTHER', 'Other')], default='OTHER', max_length=20),
        ),
        migrations.DeleteModel(
            name='Source',
        ),
    ]
