# Generated by Django 5.2.3 on 2025-06-28 15:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RatingCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session', models.CharField(db_index=True, default='0', max_length=150, verbose_name='Session')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('value', models.IntegerField(choices=[(1, 'Нравится'), (2, 'Не нравится')])),
                ('quote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.quote')),
            ],
            options={
                'ordering': ('-timestamp',),
                'indexes': [models.Index(fields=['-timestamp', 'value'], name='main_rating_timesta_1517cd_idx')],
                'unique_together': {('quote', 'session')},
            },
        ),
    ]
