# Generated by Django 5.2.3 on 2025-06-27 15:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_quote_source_quote_source_type_delete_source'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quote',
            name='source_type',
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('type', models.CharField(choices=[('BOOK', 'Book'), ('MUSIC', 'Music'), ('MOVIE', 'Movie'), ('SERIES', 'Series'), ('CARTOON', 'Cartoon'), ('OTHER', 'Other')], default='OTHER', max_length=20)),
            ],
            options={
                'unique_together': {('name', 'type')},
            },
        ),
        migrations.AlterField(
            model_name='quote',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.source'),
        ),
    ]
