# Generated by Django 5.2.3 on 2025-07-01 14:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_ratingcount'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [

        migrations.AddField(
            model_name='ratingcount',
            name='user',
            field=models.ForeignKey(null=True, blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='viewcount',
            name='user',
            field=models.ForeignKey(null=True, blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='quote',
            name='prob_rate',
            field=models.PositiveIntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='ratingcount',
            name='value',
            field=models.IntegerField(choices=[(1, 'Нравится'), (-1, 'Не нравится')]),
        ),
        migrations.AlterUniqueTogether(
            name='ratingcount',
            unique_together={('quote', 'user')},
        ),
        migrations.AlterUniqueTogether(
            name='viewcount',
            unique_together={('quote', 'user')},
        ),
        migrations.RemoveField(
            model_name='ratingcount',
            name='session',
        ),
        migrations.RemoveField(
            model_name='viewcount',
            name='session',
        ),
    ]
