# Generated by Django 5.2.3 on 2025-06-27 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_quote_source_type_source_alter_quote_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='source',
            name='type',
            field=models.CharField(choices=[('КНИГА', 'Книга'), ('МУЗЫКА', 'Музыка'), ('ФИЛЬМ', 'Фильм'), ('СЕРИАЛ', 'Сериал'), ('МУЛЬТФИЛЬМ', 'Мультфильм'), ('ДРУГОЕ', 'Другое')], default='OTHER', max_length=20),
        ),
    ]
