# Generated by Django 5.2.3 on 2025-06-27 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_source_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='prob_rate',
            field=models.PositiveIntegerField(default=2),
        ),
    ]
